[github]
# GitHub repository owner
repo_owner = YARAHQ
# GitHub repository name
repo_name = yara-forge
# GitHub API URL pattern (use %s for owner and name placeholders)
api_url = https://api.github.com/repos/%s/%s/releases/latest

[download]
# Folder to store downloaded YARA rules
folder = yara-rules
# Pattern to match the full rules package
package_pattern = full.zip
